### ISSUE TITLE
neovim-cn邀请函

### ISSUE THREAD

**Issue by wsdjeg** [BohrShaw/vish#2]
你好，首先请原谅我使用中文，我在知乎上面看到你就neovim这个项目做的回答。我想你应该也是比较喜欢这个项目的，我做了一个neovim-cn的组织，希望可以邀请你参加。
这个组织主要用来翻译一些neovim相比较vim的新特特性，以及由此而产生的一些插件的使用技巧。

王世东
2016-05-04

**Comment by BohrShaw** [comment]
感谢你“隆重”的邀请，我粗略看了一下这个组织，目前主要是在做翻译的工作，我没有时间唉。

因为[vim_diff.txt](https://github.com/neovim/neovim/blob/master/runtime/doc/vim_diff.txt)只是Vim文档的一部分，我 建议把你的翻译合并到现有的[文档翻译](http://www.vim.org/translations.php)中。不过现有的文档翻译也需要建立一个Github项目，这样可以方便大家完善。

关于插件技巧的分享，我没有写过做过类似的文章。以后可能会在博客上分享，但是目前我的分享方式主要是我的这个项目，代码为主。

中文我最爱：） So nice!

**Comment by wsdjeg** [comment]
目前希望你能参加，让这个组织活跃起来，关于文档翻译，我会找人在做，我们可以负责校验。另外我是真的感觉国内的vim用户不够活跃，其实你可以看看vim-jp，这个这组织，每年定期会有一个交流的现场会议，效果做的非常好，而且我看到绝大多数活跃的插件都是这个组织的人在写。

**Comment by BohrShaw** [comment]
我保留意见。到我能做点事情的时候再加入吧。你可以联系vim-cn，线下交流我也十分乐意。
